apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord-default
    receivers:
      - uid: discord-critical
        type: discord
        settings:
          url: https://discord.com/api/webhooks/1501768425050079252/zNc4s6keOfPQkpk9LC2z2otKmN4x6fYkBH-KfIKe_74ZI4cVUcnbHlWlQ87c8HW8hJvD
          title: "{{ .CommonLabels.alertname }}"
          message: |
            **Status:** {{ .Status | toUpper }}
            {{ range .Alerts }}
            **{{ .Labels.alertname }}** ({{ .Labels.severity }})
            Tier: {{ .Labels.tier }}
            {{ .Annotations.summary }}
            {{ range $key, $value := .Values }}
            **{{ $key }}**: {{ printf "%.4f" $value }}
            {{ end }}
            {{ end }}
        disableResolveMessage: false

  - orgId: 1
    name: discord-critical
    receivers:
      - uid: discord-page
        type: discord
        settings:
          url: https://discord.com/api/webhooks/1501768425050079252/zNc4s6keOfPQkpk9LC2z2otKmN4x6fYkBH-KfIKe_74ZI4cVUcnbHlWlQ87c8HW8hJvD
          title: "SLO Breach - {{ .CommonLabels.alertname }}"
          message: |
            **FIRING - {{ .Status | toUpper }}**
            {{ range .Alerts }}
            **{{ .Labels.alertname }}**
            Severity: {{ .Labels.severity }} | Tier: {{ .Labels.tier }}
            {{ .Annotations.summary }}
            {{ range $key, $value := .Values }}
            **{{ $key }}**: {{ printf "%.4f" $value }}
            {{ end }}
            {{ end }}
          use_discord_username: true
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: discord-default
    group_by: ["alertname", "severity"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - match:
          severity: critical
        receiver: discord-critical
        repeat_interval: 1h
        continue: false
